#!/bin/sh

riscv64-unknown-elf-as -Isrc -o famchain.o famchain.S || exit 1
riscv64-unknown-elf-objcopy -O binary famchain.o famchain.bin || exit 1

qemu-system-riscv64 \
	-machine virt \
	-nographic \
	-bios none \
	-device loader,file=./famchain.bin,addr=0x80000000 || exit 1
