#!/bin/sh

riscv64-unknown-elf-as -Isrc -o famchain.o famchain.S || exit 1
riscv64-unknown-elf-objcopy -O binary famchain.o famchain.bin || exit 1

qemu-system-riscv64 \
	-machine virt \
	-nographic \
	-bios none \
	-smp 4 \
	-device loader,file=./famchain.bin,addr=0x80000000 \
        -drive file=./tmp/disk.img,if=none,format=raw,id=dr0 \
        -device virtio-blk-device,drive=dr0,bus=virtio-mmio-bus.0 \
        -netdev user,id=net0 \
        -device virtio-net-device,netdev=net0,bus=virtio-mmio-bus.1 || exit 1;
