#!/bin/sh

riscv64-unknown-elf-as \
	-march=rv32i_zicsr \
	-mabi=ilp32 \
	-o ./tmp/stage0.o \
	stage0.S || exit 1
riscv64-unknown-elf-objcopy \
	-O binary \
	./tmp/stage0.o \
	./tmp/stage0.bin || exit 1

qemu-system-riscv32 \
      -machine virt \
      -nographic \
      -bios none \
      -smp 1 \
      -device loader,file=./tmp/stage0.bin,addr=0x80000000 \
      -netdev user,id=net0,hostfwd=tcp::2222-:22 \
      -drive file=./tmp/disk.img,if=none,format=raw,id=dr0 \
      -device virtio-blk-device,drive=dr0,bus=virtio-mmio-bus.0 \
      -device virtio-net-device,netdev=net0,bus=virtio-mmio-bus.1
