#!/bin/sh

riscv64-unknown-elf-as -march=rv32i_zicsr -mabi=ilp32 -o net.o net.S || exit 1
riscv64-unknown-elf-objcopy -O binary net.o net.bin || exit 1

qemu-system-riscv32 \
	-machine virt \
	-nographic \
	-bios none \
	-smp 1 \
	-device loader,file=./net.bin,addr=0x80000000 \
	-netdev tap,id=net0,ifname=tap0,script=no,downscript=no \
        -device virtio-net-device,netdev=net0,bus=virtio-mmio-bus.0 \
	-D /tmp/qemu.log -d trace:virtio_mmio_queue_write,trace:virtio_mmio_read,trace:virtio_mmio_write_offset,trace:virtio_mmio_guest_page,trace:virtio_queue_notify,trace:virtio_mmio_setting_irq || exit 1;
