#!/bin/sh

riscv64-unknown-elf-as \
	-march=rv32i \
	-mabi=ilp32 \
	-o ./tmp/test.o \
	test.S || exit 1
riscv64-unknown-elf-objcopy \
	-O binary \
	./tmp/test.o \
	./tmp/test.bin || exit 1

qemu-system-riscv32 \
        -machine virt \
        -nographic \
        -bios none \
        -smp 1 \
        -device loader,file=./tmp/test.bin,addr=0x80000000 \
        -drive file=./tmp/disk.img,if=none,format=raw,id=dr0 \
        -device virtio-blk-device,drive=dr0,bus=virtio-mmio-bus.0 \
        -netdev user,id=net0,hostfwd=tcp::2222-:22 \
        -device virtio-net-device,netdev=net0,bus=virtio-mmio-bus.1 \
        -global virtio-mmio.force-legacy=on \
	-object filter-dump,id=f1,netdev=net0,file=/tmp/guest.pcap \
	-d trace:virtio* \
	-D /tmp/qemu.log
